wip
Signed-off-by: Joe Isaacs <joe.isaacs@live.co.uk>

diff --git a/.github/workflows/minimize_fuzz_corpus_workflow.yml b/.github/workflows/minimize_fuzz_corpus_workflow.yml
--- a/.github/workflows/minimize_fuzz_corpus_workflow.yml
+++ b/.github/workflows/minimize_fuzz_corpus_workflow.yml
@@ -39,6 +39,12 @@ jobs:
       - extras=s3-cache
       - tag=${{ inputs.fuzz_target }}-minimize
     steps:
+      - name: Bail if not on develop
+        if: github.ref != 'refs/heads/develop'
+        run: |
+          echo "::error::Corpus minimization should only run on the develop branch (current: ${{ github.ref }})"
+          exit 1
+
       - uses: runs-on/action@v2
         with:
           sccache: s3
